server:
  port: 2000

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      repositories:
        enabled: false

bot:
  mode: development
  token: ${BOT_TOKEN}
  domain: ${BOT_DOMAIN:}
  username: ${BOT_USERNAME:}
  properties:
    catch-mapper-exception: true
    show-unmapped-request-log: true
  i18:
    enabled: true
    key:
      back-button: back-button
      contact-button: phone-button
      location-button: location-button
      back-button-prefix: BACK_


spotify:
  client-id: #{SPOTIFY_CLIENT_ID}#
  client-secret: #{SPOTIFY_CLIENT_SECRET}#






